package com.exceptions;

public class ExceptionHandling {
	public static void main(String args[]) {
		try {
			int a = 0;
			int b = 0;
			
		
			int array [] = new  int [2];
			int sum = a / b;
			
		} 	catch(ArithmeticException e) {
		
			System.out.println("division by error");
		
		}


	}
}
